apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: santhosh2969/java:v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: ms
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30201
  selector:
    app: demo
